//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_servis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ispit
    {
        public int idIspit { get; set; }
        public string Naziv { get; set; }
        public System.DateTime Datum { get; set; }
        public int Aktivan { get; set; }
    }
}
