//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_servis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentIspit
    {
        public int id_Student { get; set; }
        public int id_Ispit { get; set; }
        public int Ocena { get; set; }
    }
}
