//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_servis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int idStudent { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public System.DateTime Datum_rodjenja { get; set; }
        public string Broj_index { get; set; }
        public int Aktivan { get; set; }
    }
}
